import React, { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 默认翻译字典
const translations = {
  zh: {
    // 通用
    'app.name': 'Intentorch',
    'app.subtitle': 'MCP 服务管理平台',
    'common.loading': '加载中...',
    'common.search': '搜索',
    'common.search.placeholder': '搜索服务器、进程或日志...',
    'common.search.results': '搜索结果',
    'common.search.noResults': '未找到匹配的结果',
    'common.search.servers': '服务器',
    'common.search.processes': '进程',
    'common.search.logs': '日志',
    'common.search.viewAllResults': '查看所有结果',
    'common.searching': '搜索中...',
    'common.close': '关闭',
    'common.status': '状态',
    'common.actions': '操作',
    'common.details': '详情',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.refresh': '刷新',
    'common.confirm': '确认',
    'common.yes': '是',
    'common.no': '否',
    
    // 布局
    'layout.dashboard': '仪表板',
    'layout.serverManagement': 'MCP服务',
    'layout.processMonitoring': '进程监控',
    'layout.workflowOrchestration': '工作流',
    'layout.configurationManagement': '配置',
    'layout.secretsManagement': '密钥',
    'layout.logViewer': '日志',
    'layout.systemStatus': '系统状态',
    'layout.running': '运行中',
    'layout.logout': '退出登录',
    'layout.footer.copyright': '© {year} Intentorch - 意图驱动的MCP服务编排引擎',
    'layout.footer.version': '版本',
    'layout.footer.status': '状态',
    'layout.footer.connecting': '连接中...',
    'layout.footer.runningNormally': '运行正常',
    'layout.footer.wechat': '微信',
    'layout.footer.wechatTitle': '关注微信公众号',
    'layout.footer.wechatScan': '扫描关注Intentorch',
    'layout.footer.qqGroup': 'QQ群',
    'layout.footer.qqGroupTitle': '加入QQ群',
    'layout.footer.qqGroupScan': '扫描加入QQ群',
    'layout.footer.github': 'GitHub',
    'layout.footer.githubTitle': 'GitHub仓库',
    'layout.footer.gitee': 'Gitee',
    'layout.footer.giteeTitle': 'Gitee仓库',
    'layout.footer.emailTitle': '发送邮件',
    
    // 仪表板
    'dashboard.title': '仪表板',
    'dashboard.welcome': '欢迎使用Intentorch管理控制台，这里是您的MCP Server管理中心。',
    'dashboard.totalServers': '总服务器数',
    'dashboard.runningServers': '运行中服务器',
    'dashboard.runningServersTitle': '运行中的服务器',
    'dashboard.runningServersDescription': '当前正在运行的MCP Server进程',
    'dashboard.noRunningServers': '当前没有运行中的服务器',
    'dashboard.recentActivitiesTitle': '最近活动',
    'dashboard.recentActivitiesDescription': '系统最近的操作记录',
    'dashboard.quickActions': '快速操作',
    'dashboard.quickActionsDesc': '常用功能的快捷入口',
    'dashboard.addServer': '添加服务器',
    'dashboard.addServerDesc': '从注册表拉取',
    'dashboard.startAll': '启动所有',
    'dashboard.startAllDesc': '启动已停止的服务器',
    'dashboard.clearCache': '清理缓存',
    'dashboard.clearCacheDesc': '释放磁盘空间',
    'dashboard.viewLogs': '查看日志',
    'dashboard.viewLogsDesc': '系统运行日志',
    'dashboard.serverOverviewTitle': '服务器状态概览',
    'dashboard.serverOverviewDescription': '所有MCP Server的状态分布',
    'dashboard.serverName': '服务器名称',
    'dashboard.version': '版本',
    'dashboard.lastOperation': '最后操作',
    'dashboard.pull': '拉取',
    'dashboard.start': '启动',
    'dashboard.stop': '停止',
    'dashboard.noServerData': '暂无服务器数据',
    'dashboard.comparedToYesterday': '相比昨天',
    'dashboard.noDescription': '暂无描述',
    'dashboard.neverStarted': '从未启动',
    'dashboard.actions': '操作',
    'dashboard.details': '详情',
    'dashboard.noActivities': '暂无活动记录',
    
    // 状态
    'status.running': '运行中',
    'status.stopped': '已停止',
    'status.error': '错误',
    'status.pulled': '已拉取',
    'status.not_pulled': '未拉取',
    'status.starting': '启动中',
    'status.stopping': '停止中',
    
    // 时间
    'time.justNow': '刚刚',
    'time.minutesAgo': '{minutes}分钟前',
    'time.hoursAgo': '{hours}小时前',
    'time.daysAgo': '{days}天前',
    'time.neverStarted': '从未启动',
    
    // Servers页面
    'servers.title': 'MCP服务',
    'servers.subtitle': '管理您的MCP服务器及其进程',
    'servers.pullNewServer': '拉取新服务器',
    'servers.pullButton': '拉取服务器',
    'servers.pullingButton': '拉取中...',
    'servers.pullPlaceholder': '输入服务器URL或名称（例如：modelscope://username/repo）',
    'servers.pullDescription': '输入服务器URL或名称以从注册表拉取',
    'servers.availableServers': '可用服务器',
    'servers.availableServersDesc': '注册表中可用的MCP服务器列表',
    'servers.noServers': '暂无服务器',
    'servers.noServersDesc': '从注册表拉取服务器开始使用',
    'servers.serverName': '服务器名称',
    'servers.version': '版本',
    'servers.status': '状态',
    'servers.start': '启动',
    'servers.stop': '停止',
    'servers.confirmStop': '确定要停止此服务器吗？',
    'servers.error.loadFailed': '加载服务器失败',
    'servers.error.pullFailed': '拉取服务器失败',
    'servers.error.stopFailed': '停止服务器失败',
    'servers.error.startFailed': '启动服务器失败',
    'servers.error.urlRequired': '请输入服务器URL或名称',
    'servers.searchNotAvailable': '搜索功能暂不可用，请手动输入服务器名称',
    'servers.noSearchResults': '未找到匹配的服务器',
    'servers.error.searchFailed': '搜索失败',
    'servers.registrySource': '注册表源',
    'servers.searchServers': '搜索服务器',
    'servers.searchPlaceholder': '搜索{source}...',
    'servers.searchComingSoon': '搜索功能即将推出',
    'servers.serverIdentifier': '服务器标识符',
    'servers.showExamples': '显示示例',
    'servers.hideExamples': '隐藏示例',
    'servers.examplesFor': '{source}的示例：',
    'servers.enterIdentifier': '输入{source}的服务器标识符...',
    'servers.format': '格式：',
    'servers.format.official': 'mcp/服务器名称',
    'servers.format.github': '所有者/仓库[@分支][:路径]',
    'servers.format.gitee': '服务器名称',
    'servers.format.direct': 'URL或文件路径',
    'servers.supports.github': '支持：所有者/仓库、所有者/仓库@分支、所有者/仓库:路径/to/mcp.json',
    'servers.supports.direct': '支持：https://...、http://...、file://...、或本地文件路径',
    'servers.pulledServers': '已拉取的服务器',
    'servers.pulledServersDescription': '这些是已经从注册表拉取并可在本地启动的服务器。注意：有些服务器可能没有本地缓存文件。',
    'servers.downloadUrlInfo': '下载URL信息',
    'servers.downloadUrlDescription': '所选注册表源 <span class="font-medium">{sourceName}</span> 的MCP服务下载URL：',
    'servers.githubSourceDescription': 'GitHub源',
    'servers.giteeSourceDescription': 'Gitee源',
    'servers.directSourceDescription': '直接源：使用直接URL或本地文件路径',
    
    // Processes页面
    'processes.title': '进程监控',
    'processes.subtitle': '监控和管理所有MCP Server进程的运行状态',
    'processes.totalProcesses': '总进程数',
    'processes.running': '运行中',
    'processes.stopped': '已停止',
    'processes.error': '错误',
    'processes.searchPlaceholder': '搜索进程名称或ID...',
    'processes.filterAll': '所有状态',
    'processes.filterRunning': '运行中',
    'processes.filterStopped': '已停止',
    'processes.filterError': '错误',
    'processes.refresh': '刷新',
    'processes.processInfo': '进程信息',
    'processes.status': '状态',
    'processes.resourceUsage': '资源使用',
    'processes.startTime': '启动时间',
    'processes.actions': '操作',
    'processes.stopProcess': '停止进程',
    'processes.startProcess': '启动进程',
    'processes.viewLogs': '查看日志',
    'processes.moreActions': '更多操作',
    'processes.noMatchingProcesses': '未找到匹配的进程',
    'processes.clearSearch': '清除搜索条件',
    'processes.batchOperations': '批量操作',
    'processes.batchOperationsDesc': '对选定的进程执行批量操作',
    'processes.startSelected': '启动选定',
    'processes.stopSelected': '停止选定',
    'processes.deleteSelected': '删除选定',
    'processes.logsTitle': '{serverName} 日志',
    'processes.logsSubtitle': 'PID: {pid} • 最后更新: {time}',
    'processes.logFile': '日志文件',
    'processes.refreshLogs': '刷新日志',
    'processes.downloadLogs': '下载日志',
    'processes.confirmStop': '确定要停止此进程吗？',
    'processes.loading': '加载进程数据...',
    
    // Config页面
    'config.title': '配置',
    'config.subtitle': '配置AI提供商和注册表设置',
    'config.aiConfiguration': 'AI配置',
    'config.provider': '提供商',
    'config.providerPlaceholder': '例如：openai, anthropic',
    'config.selectProvider': '选择提供商',
    'config.providerDescription': '选择您的AI服务提供商',
    'config.model': '模型',
    'config.modelPlaceholder': '例如：gpt-4, claude-3',
    'config.selectModel': '选择模型',
    'config.modelDescription': '选择适合您需求的模型',
    'config.customModelDescription': '输入自定义模型名称',
    'config.selectProviderFirst': '请先选择提供商',
    'config.apiKey': 'API密钥',
    'config.apiKeyPlaceholder': '输入您的API密钥',
    'config.apiKeyDescription': '您的API密钥安全存储，永远不会发送到我们的服务器。',
    'config.registryConfiguration': '注册表配置',
    'config.defaultRegistry': '默认注册表',
    'config.selectDefaultRegistry': '选择默认注册表',
    'config.fallbackRegistry': '备用注册表',
    'config.selectFallbackRegistry': '选择备用注册表',
    'config.reset': '重置',
    'config.saveConfiguration': '保存配置',
    'config.saving': '保存中...',
    'config.currentConfiguration': '当前配置',
    'config.aiSettings': 'AI设置',
    'config.registrySettings': '注册表设置',
    'config.error.loadFailed': '加载配置失败',
    'config.error.saveFailed': '保存配置失败',
    'config.testConfiguration': '测试配置',
    'config.testing': '测试中...',
    'config.testSuccess': '配置测试成功！',
    'config.testError': '配置测试失败',
    'config.testErrorMissingFields': '请填写提供商、模型和API密钥以测试配置',
    'config.testErrorUnknown': '未知错误',
    'config.testDescription': '测试当前AI配置是否生效',
    
    // Secrets页面
    'secrets.title': '密钥',
    'secrets.subtitle': '管理您的敏感API密钥和凭据',
    'secrets.createNewSecret': '创建新密钥',
    'secrets.cancel': '取消',
    'secrets.secretName': '密钥名称',
    'secrets.secretNamePlaceholder': '例如：OPENAI_API_KEY',
    'secrets.secretValue': '密钥值',
    'secrets.secretValuePlaceholder': '输入密钥值',
    'secrets.description': '描述（可选）',
    'secrets.descriptionPlaceholder': '描述此密钥的用途',
    'secrets.createSecret': '创建密钥',
    'secrets.creating': '创建中...',
    'secrets.storedSecrets': '存储的密钥',
    'secrets.storedSecretsDescription': '您的密钥已加密并安全存储',
    'secrets.noSecrets': '暂无密钥',
    'secrets.noSecretsDescription': '创建您的第一个密钥开始使用',
    'secrets.lastUpdated': '最后更新',
    'secrets.delete': '删除',
    'secrets.confirmDelete': '确定要删除密钥"{name}"吗？',
    'secrets.securityNotice': '安全提示',
    'secrets.securityNotice1': '• 密钥已加密并存储在您的本地机器上',
    'secrets.securityNotice2': '• 切勿分享您的密钥或将其提交到版本控制',
    'secrets.securityNotice3': '• 在生产环境中使用环境变量存储敏感数据',
    'secrets.error.loadFailed': '加载密钥失败',
    'secrets.error.createFailed': '创建密钥失败',
    'secrets.error.deleteFailed': '删除密钥失败',
    
    // Login页面
    'login.title': 'IntentOrch 登录',
    'login.subtitle': '请输入守护进程生成的认证令牌以访问管理控制台',
    'login.authenticationToken': '认证令牌',
    'login.tokenPlaceholder': '输入守护进程生成的令牌',
    'login.tokenDescription': '令牌在守护进程启动时自动生成，可在控制台输出中找到',
    'login.login': '登录',
    'login.loggingIn': '登录中...',
    'login.getTokenFromDaemon': '从守护进程获取令牌',
    'login.howToGetToken': '如何获取令牌？',
    'login.step1': '启动守护进程，在终端执行以下命令：',
    'login.rememberToken': '记住此令牌',
    'login.rememberTokenHint': '下次自动填充令牌',
    'login.showToken': '显示令牌',
    'login.hideToken': '隐藏令牌',
    'login.pasteFromClipboard': '粘贴',
    'login.clearInput': '清空',
    'login.daemonStatus.connected': '守护进程已连接',
    'login.daemonStatus.disconnected': '守护进程未连接',
    'login.daemonStatus.checking': '检查守护进程状态...',
    'login.error.cannotConnect': '无法连接到守护进程，请检查守护进程是否正在运行',
    'login.error.authenticationFailed': '认证失败',
    'login.error.tokenNotFound': '在守护进程响应中未找到令牌',
    'login.error.cannotGetToken': '无法从守护进程获取令牌',
    'login.error.invalidToken': '令牌无效，请检查令牌是否正确',
    'login.error.serverError': '服务器错误，请稍后重试',
    'login.error.networkError': '网络连接失败，请检查网络设置',
    'login.tokenObtained': '✓ 已成功获取令牌',
    'login.tokenPasted': '✓ 已从剪贴板粘贴',
    'login.tokenCleared': '已清空令牌',
    'login.tokenRemembered': '已记住令牌，下次自动填充',
    'login.tokenForgotten': '已清除记住的令牌',
    'login.connecting': '连接中...',
    'login.retry': '重试',
    'login.or': '或',
    'login.quickStart': '快速开始',
    'login.quickStartDesc': '如果您是首次使用，请先启动守护进程：',
    'login.needHelp': '需要帮助？',
    'login.contactSupport': '联系支持',
    'login.viewDocs': '查看文档',
    'login.tagline': '您说，MCP 做',
    'login.welcome': '欢迎回来',
    'login.welcomeMessage': '输入您的认证令牌以继续',
    'login.tokenInputLabel': '认证令牌输入区域',
    'login.tokenHelp': '令牌是访问管理控制台的唯一凭证，请妥善保管',
    'login.tokenAutoFilled': '已自动填充保存的令牌',
    'login.tokenAutoFilledDesc': '点击"登录"按钮即可验证',
    'login.daemonConnected': '守护进程运行正常',
    'login.daemonDisconnected': '守护进程未运行',
    'login.daemonCheckFailed': '无法检测守护进程状态',
    'login.error.invalidFormat': '令牌格式不正确，请检查是否完整复制',
    'login.error.tokenExpired': '令牌已过期，请重新获取',
    'login.error.unauthorized': '未授权，请检查令牌权限',
    'login.error.unknown': '发生未知错误，请稍后重试',
    'login.tokenCopied': '令牌已复制到剪贴板',
    'login.copyToken': '复制令牌',
    'login.tokenCopiedHint': '令牌已复制，请妥善保管',
    'login.tokenSecurityTip': '请勿将令牌分享给他人或提交到版本控制',
    'login.tokenSecurityTitle': '安全提示',
    'login.tokenSecurityDesc': '令牌是您访问管理控制台的唯一凭证，请妥善保管，不要分享给他人。',
    'login.tokenInputHelp': '在终端中运行 intentorch daemon start，复制输出的令牌粘贴到上方',
    'login.tokenInputHelpTitle': '如何获取令牌？',
    'login.tokenInputHelpStep1': '打开终端，执行：',
    'login.tokenInputHelpStep2': '在输出中找到 Token 行，复制完整令牌',
    'login.tokenInputHelpStep3': '粘贴到上方输入框中，点击登录',
    'login.tokenInputHelpAction': '复制命令',
    'login.tokenInputHelpCopied': '命令已复制',
    'login.tokenInputHelpTip': '提示：您也可以点击下方按钮自动获取令牌',
    'login.tokenInputHelpTipAction': '自动获取',
    'login.tokenInputHelpTipDesc': '从本地守护进程自动获取令牌',
    'login.tokenInputHelpTipSuccess': '已自动获取令牌',
    'login.tokenInputHelpTipFailed': '自动获取失败，请手动输入',
    'login.tokenInputHelpTipChecking': '正在获取...',
    'login.tokenInputHelpTipRetry': '重试',
    'login.tokenInputHelpTipClose': '关闭',
    'login.tokenInputHelpTipError': '获取失败',
    'login.tokenInputHelpTipErrorDesc': '无法从守护进程获取令牌，请手动输入',
    'login.tokenInputHelpTipErrorAction': '手动输入',
    'login.tokenInputHelpTipSuccessDesc': '已成功获取令牌，请点击登录',
    'login.tokenInputHelpTipSuccessAction': '登录',
    'login.tokenInputHelpTipCheckingDesc': '正在从守护进程获取令牌...',
    'login.tokenInputHelpTipCheckingCancel': '取消',
    'login.tokenInputHelpTipRetryDesc': '获取令牌失败，请重试或手动输入',
    'login.tokenInputHelpTipRetryAction': '重试',
    
    // Logs页面
    'logs.title': '日志',
    'logs.subtitle': '查看和分析系统、Server和工作流的运行日志',
    'logs.totalLogs': '总日志数',
    'logs.errorLogs': '错误日志',
    'logs.warningLogs': '警告日志',
    'logs.todayLogs': '今日日志',
    'logs.searchPlaceholder': '搜索日志内容或来源...',
    'logs.autoRefresh': '自动刷新',
    'logs.refresh': '刷新',
    'logs.logLevel': '日志级别',
    'logs.allLevels': '所有级别',
    'logs.error': '错误',
    'logs.warning': '警告',
    'logs.info': '信息',
    'logs.debug': '调试',
    'logs.logSource': '日志来源',
    'logs.allSources': '所有来源',
    'logs.systemLogs': '系统日志',
    'logs.serverLogs': 'Server日志',
    'logs.workflowLogs': '工作流日志',
    'logs.timeRange': '时间范围',
    'logs.today': '今天',
    'logs.yesterday': '昨天',
    'logs.last7Days': '最近7天',
    'logs.last30Days': '最近30天',
    'logs.allTime': '全部时间',
    'logs.showingLogs': '显示 {count} 条日志记录',
    'logs.exportLogs': '导出日志',
    'logs.clearLogs': '清空日志',
    'logs.collapseDetails': '收起详情',
    'logs.expandDetails': '展开详情',
    'logs.copyLog': '复制日志',
    'logs.viewSourceDetails': '查看来源详情',
    'logs.noLogs': '暂无日志记录',
    'logs.noLogsDescription': '当前没有日志记录',
    'logs.noMatchingLogs': '没有找到匹配的日志记录',
    'logs.clearAllFilters': '清除所有筛选条件',
    'logs.levelDistribution': '日志级别分布',
    'logs.levelDistributionDesc': '按级别统计的日志数量',
    'logs.sourceDistribution': '日志来源分布',
    'logs.sourceDistributionDesc': '按来源统计的日志数量',
    'logs.system': '系统',
    'logs.server': 'Server',
    'logs.workflow': '工作流',
    'logs.logCopied': '日志已复制到剪贴板',
    'logs.noLogsToExport': '没有日志可导出',
    'logs.confirmClearLogs': '确定要清空所有日志吗？此操作无法撤销。',
    'logs.logsCleared': '日志已清空',
    
    // Workflows页面
    'workflows.title': '工作流',
    'workflows.description': '创建和管理自动化工作流',
    'workflows.createWorkflow': '创建工作流',
    'workflows.totalWorkflows': '总工作流数',
    'workflows.executedWorkflows': '已执行工作流',
    'workflows.neverExecutedWorkflows': '未执行工作流',
    'workflows.workflowsWithSteps': '有步骤定义的工作流',
    'workflows.noWorkflows': '暂无工作流',
    'workflows.searchPlaceholder': '搜索工作流名称或描述...',
    'workflows.filterAll': '所有工作流',
    'workflows.filterHasSteps': '有步骤定义',
    'workflows.filterExecuted': '已执行过',
    'workflows.filterNeverExecuted': '从未执行',
    'workflows.exportAll': '导出所有工作流',
    'workflows.importWorkflow': '导入工作流',
    'workflows.refresh': '刷新',
    'workflows.createModalTitle': '创建工作流',
    'workflows.createModalSubtitle': '创建新的自动化工作流',
    'workflows.editModalTitle': '编辑工作流',
    'workflows.editModalSubtitle': '编辑工作流基本信息',
    'workflows.nameRequired': '工作流名称 *',
    'workflows.descriptionOptional': '描述（可选）',
    'workflows.cancel': '取消',
    'workflows.save': '保存',
    'workflows.creating': '创建中...',
    'workflows.saving': '保存中...',
    'workflows.execute': '执行',
    'workflows.edit': '编辑',
    'workflows.duplicate': '复制',
    'workflows.exportJson': '导出为JSON',
    'workflows.delete': '删除',
    'workflows.steps': '步骤',
    'workflows.created': '创建时间',
    'workflows.lastExecuted': '最后执行',
    'workflows.workflowId': '工作流ID',
    'workflows.stepsCount': '步骤数量',
    'workflows.lastUpdated': '最后更新',
    'workflows.noDescription': '无描述',
    'workflows.noMatchingWorkflows': '未找到匹配的工作流',
    'workflows.createFirstWorkflow': '创建第一个工作流',
    'workflows.confirmDelete': '确定要删除工作流"{name}"吗？',

    // Orchestration (意图编排)
    'orchestration.title': '意图编排',
    'orchestration.aiAssistant': 'AI助手',
    'orchestration.subtitle': '通过自然语言描述，自动生成自动化工作流',
    'orchestration.chatPlaceholder': '输入您的自动化需求...',
    'orchestration.inputPlaceholder': '输入您的意图',
    'orchestration.sendButton': '发送 (Enter)',
    'orchestration.analyzing': '正在解析意图...',
    'orchestration.publish': '发布工作流',
    'orchestration.clear': '清空草稿',
    'orchestration.noDraft': '暂无草稿',
    'orchestration.capabilityMissing': '未找到匹配能力',
    'orchestration.capabilityMissingDesc': '我无法找到匹配的 MCP Server 或工具来满足您的需求。',
    'orchestration.submitRequest': '提交工具请求',
    'orchestration.workflowGenerated': '我为您生成了一个包含 {count} 个步骤的工作流。请在右侧查看步骤并执行。',
    'orchestration.executionComplete': '工作流执行完成。',
    'orchestration.formattingFailed': '工作流执行完成，但结果格式化失败。',
    'orchestration.generatingWorkflow': '生成工作流中...',
    'orchestration.executeNow': '立即执行',
    'orchestration.executeNowDesc': '保存并立即执行',
    'orchestration.saveOnly': '仅保存',
    'orchestration.saveOnlyDesc': '保存以供稍后执行',
    'orchestration.editSteps': '编辑步骤',
    'orchestration.editStepsDesc': '查看并修改步骤',
    'orchestration.stepsGenerated': '已生成 {count} 个步骤',
    'orchestration.clearAllSteps': '清空所有步骤',
    'orchestration.selectAction': '选择操作',
    'orchestration.executing': '执行中...',
    'orchestration.go': '执行',
    'orchestration.chooseAction': '选择操作',
    'orchestration.actionTip': '提示：选择的操作将被记住，下次使用',
    'orchestration.addStepManually': '手动添加步骤',
    'orchestration.contactSupport': '联系支持',
    'orchestration.failedToGenerate': '生成工作流失败。请尝试重新表述您的意图。',
    'orchestration.draftMode': '草稿模式 • 本地自动保存',
    'orchestration.executingWorkflow': '执行工作流',
    'orchestration.pleaseWaitWorkflow': '请稍候，工作流正在执行中...',
    'orchestration.poweredBy': '由 Intentorch 推理引擎驱动',
  },
  en: {
    // Common
    'app.name': 'Intentorch',
    'app.subtitle': 'MCP Server Management',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.search.placeholder': 'Search servers, processes or logs...',
    'common.search.results': 'Search Results',
    'common.search.noResults': 'No matching results found',
    'common.search.servers': 'Servers',
    'common.search.processes': 'Processes',
    'common.search.logs': 'Logs',
    'common.search.viewAllResults': 'View all results',
    'common.searching': 'Searching...',
    'common.close': 'Close',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.refresh': 'Refresh',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Layout
    'layout.dashboard': 'Dashboard',
    'layout.serverManagement': 'MCP Services',
    'layout.processMonitoring': 'Process Monitoring',
    'layout.workflowOrchestration': 'Workflows',
    'layout.configurationManagement': 'Configuration',
    'layout.secretsManagement': 'Secrets',
    'layout.logViewer': 'Logs',
    'layout.systemStatus': 'System Status',
    'layout.running': 'Running',
    'layout.logout': 'Logout',
    'layout.footer.copyright': '© {year} Intentorch - Intent-driven MCP orchestration',
    'layout.footer.version': 'Version',
    'layout.footer.status': 'Status',
    'layout.footer.connecting': 'Connecting...',
    'layout.footer.runningNormally': 'Running normally',
    'layout.footer.wechat': 'WeChat',
    'layout.footer.wechatTitle': 'Follow WeChat Official Account',
    'layout.footer.wechatScan': 'Scan to follow Intentorch',
    'layout.footer.qqGroup': 'QQ Group',
    'layout.footer.qqGroupTitle': 'Join QQ Group',
    'layout.footer.qqGroupScan': 'Scan to join QQ Group',
    'layout.footer.github': 'GitHub',
    'layout.footer.githubTitle': 'GitHub Repository',
    'layout.footer.gitee': 'Gitee',
    'layout.footer.giteeTitle': 'Gitee Repository',
    'layout.footer.emailTitle': 'Send Email',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Intentorch management console, your MCP Server management center.',
    'dashboard.totalServers': 'Total Servers',
    'dashboard.runningServers': 'Running Servers',
    'dashboard.runningServersTitle': 'Running Servers',
    'dashboard.runningServersDescription': 'Currently running MCP Server processes',
    'dashboard.noRunningServers': 'No running servers currently',
    'dashboard.recentActivitiesTitle': 'Recent Activities',
    'dashboard.recentActivitiesDescription': 'Recent system operation records',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActionsDesc': 'Shortcuts for commonly used functions',
    'dashboard.addServer': 'Add Server',
    'dashboard.addServerDesc': 'Pull from registry',
    'dashboard.startAll': 'Start All',
    'dashboard.startAllDesc': 'Start stopped servers',
    'dashboard.clearCache': 'Clear Cache',
    'dashboard.clearCacheDesc': 'Free up disk space',
    'dashboard.viewLogs': 'View Logs',
    'dashboard.viewLogsDesc': 'System operation logs',
    'dashboard.serverOverviewTitle': 'Server Status Overview',
    'dashboard.serverOverviewDescription': 'Status distribution of all MCP Servers',
    'dashboard.serverName': 'Server Name',
    'dashboard.version': 'Version',
    'dashboard.lastOperation': 'Last Operation',
    'dashboard.pull': 'Pull',
    'dashboard.start': 'Start',
    'dashboard.stop': 'Stop',
    'dashboard.noServerData': 'No server data available',
    'dashboard.comparedToYesterday': 'Compared to yesterday',
    'dashboard.noDescription': 'No description',
    'dashboard.neverStarted': 'Never started',
    'dashboard.actions': 'Actions',
    'dashboard.details': 'Details',
    'dashboard.noActivities': 'No activities',
    
    // Status
    'status.running': 'Running',
    'status.stopped': 'Stopped',
    'status.error': 'Error',
    'status.pulled': 'Pulled',
    'status.not_pulled': 'Not Pulled',
    'status.starting': 'Starting',
    'status.stopping': 'Stopping',
    
    // Time
    'time.justNow': 'Just now',
    'time.minutesAgo': '{minutes} minutes ago',
    'time.hoursAgo': '{hours} hours ago',
    'time.daysAgo': '{days} days ago',
    'time.neverStarted': 'Never started',
    
    // Servers page
    'servers.title': 'MCP Services',
    'servers.subtitle': 'Manage your MCP servers and their processes',
    'servers.pullNewServer': 'Pull New Server',
    'servers.pullButton': 'Pull Server',
    'servers.pullingButton': 'Pulling...',
    'servers.pullPlaceholder': 'Enter server URL or name (e.g., modelscope://username/repo)',
    'servers.pullDescription': 'Enter a server URL or name to pull from the registry',
    'servers.availableServers': 'Available Servers',
    'servers.availableServersDesc': 'List of MCP servers available in your registry',
    'servers.noServers': 'No servers',
    'servers.noServersDesc': 'Get started by pulling a server from the registry',
    'servers.serverName': 'Server Name',
    'servers.version': 'Version',
    'servers.status': 'Status',
    'servers.start': 'Start',
    'servers.stop': 'Stop',
    'servers.confirmStop': 'Are you sure you want to stop this server?',
    'servers.error.loadFailed': 'Failed to load servers',
    'servers.error.pullFailed': 'Failed to pull server',
    'servers.error.stopFailed': 'Failed to stop server',
    'servers.error.startFailed': 'Failed to start server',
    'servers.error.urlRequired': 'Please enter a server URL or name',
    'servers.searchNotAvailable': 'Search functionality is not available, please enter server name manually',
    'servers.noSearchResults': 'No matching servers found',
    'servers.error.searchFailed': 'Search failed',
    'servers.registrySource': 'Registry Source',
    'servers.searchServers': 'Search Servers',
    'servers.searchPlaceholder': 'Search {source}...',
    'servers.searchComingSoon': 'Search functionality coming soon',
    'servers.serverIdentifier': 'Server Identifier',
    'servers.showExamples': 'Show Examples',
    'servers.hideExamples': 'Hide Examples',
    'servers.examplesFor': 'Examples for {source}:',
    'servers.enterIdentifier': 'Enter server identifier for {source}...',
    'servers.format': 'Format:',
    'servers.format.official': 'mcp/server-name',
    'servers.format.github': 'owner/repo[@branch][:path]',
    'servers.format.gitee': 'server-name',
    'servers.format.direct': 'URL or file path',
    'servers.supports.github': 'Supports: owner/repo, owner/repo@branch, owner/repo:path/to/mcp.json',
    'servers.supports.direct': 'Supports: https://..., http://..., file://..., or local file path',
    'servers.pulledServers': 'Pulled Servers',
    'servers.pulledServersDescription': 'These are servers that have been pulled from the registry and can be started locally. Note: Some servers may not have local cache files.',
    'servers.downloadUrlInfo': 'Download URL Information',
    'servers.downloadUrlDescription': 'The MCP service download URL for the selected registry source <span class="font-medium">{sourceName}</span>:',
    'servers.githubSourceDescription': 'GitHub source',
    'servers.giteeSourceDescription': 'Gitee source',
    'servers.directSourceDescription': 'Direct source: Use direct URL or local file path',
    
    // Processes page
    'processes.title': 'Process Monitoring',
    'processes.subtitle': 'Monitor and manage the running status of all MCP Server processes',
    'processes.totalProcesses': 'Total Processes',
    'processes.running': 'Running',
    'processes.stopped': 'Stopped',
    'processes.error': 'Error',
    'processes.searchPlaceholder': 'Search process name or ID...',
    'processes.filterAll': 'All Status',
    'processes.filterRunning': 'Running',
    'processes.filterStopped': 'Stopped',
    'processes.filterError': 'Error',
    'processes.refresh': 'Refresh',
    'processes.processInfo': 'Process Info',
    'processes.status': 'Status',
    'processes.resourceUsage': 'Resource Usage',
    'processes.startTime': 'Start Time',
    'processes.actions': 'Actions',
    'processes.stopProcess': 'Stop Process',
    'processes.startProcess': 'Start Process',
    'processes.viewLogs': 'View Logs',
    'processes.moreActions': 'More Actions',
    'processes.noMatchingProcesses': 'No matching processes found',
    'processes.clearSearch': 'Clear search criteria',
    'processes.batchOperations': 'Batch Operations',
    'processes.batchOperationsDesc': 'Perform batch operations on selected processes',
    'processes.startSelected': 'Start Selected',
    'processes.stopSelected': 'Stop Selected',
    'processes.deleteSelected': 'Delete Selected',
    'processes.logsTitle': '{serverName} Logs',
    'processes.logsSubtitle': 'PID: {pid} • Last updated: {time}',
    'processes.logFile': 'Log file',
    'processes.refreshLogs': 'Refresh Logs',
    'processes.downloadLogs': 'Download Logs',
    'processes.confirmStop': 'Are you sure you want to stop this process?',
    'processes.loading': 'Loading process data...',
    
    // Config page
    'config.title': 'Configuration',
    'config.subtitle': 'Configure AI providers and registry settings',
    'config.aiConfiguration': 'AI Configuration',
    'config.provider': 'Provider',
    'config.providerPlaceholder': 'e.g., openai, anthropic',
    'config.selectProvider': 'Select Provider',
    'config.providerDescription': 'Select your AI service provider',
    'config.model': 'Model',
    'config.modelPlaceholder': 'e.g., gpt-4, claude-3',
    'config.selectModel': 'Select Model',
    'config.modelDescription': 'Select the model that fits your needs',
    'config.customModelDescription': 'Enter custom model name',
    'config.selectProviderFirst': 'Please select provider first',
    'config.apiKey': 'API Key',
    'config.apiKeyPlaceholder': 'Enter your API key',
    'config.apiKeyDescription': 'Your API key is stored securely and never sent to our servers.',
    'config.registryConfiguration': 'Registry Configuration',
    'config.defaultRegistry': 'Default Registry',
    'config.selectDefaultRegistry': 'Select default registry',
    'config.fallbackRegistry': 'Fallback Registry',
    'config.selectFallbackRegistry': 'Select fallback registry',
    'config.reset': 'Reset',
    'config.saveConfiguration': 'Save Configuration',
    'config.saving': 'Saving...',
    'config.currentConfiguration': 'Current Configuration',
    'config.aiSettings': 'AI Settings',
    'config.registrySettings': 'Registry Settings',
    'config.error.loadFailed': 'Failed to load configuration',
    'config.error.saveFailed': 'Failed to save configuration',
    'config.testConfiguration': 'Test Configuration',
    'config.testing': 'Testing...',
    'config.testSuccess': 'Configuration test successful!',
    'config.testError': 'Configuration test failed',
    'config.testErrorMissingFields': 'Please fill in provider, model and API key to test configuration',
    'config.testErrorUnknown': 'Unknown error',
    'config.testDescription': 'Test if the current AI configuration works',
    
    // Secrets page
    'secrets.title': 'Secrets',
    'secrets.subtitle': 'Manage your sensitive API keys and credentials',
    'secrets.createNewSecret': 'Create New Secret',
    'secrets.cancel': 'Cancel',
    'secrets.secretName': 'Secret Name',
    'secrets.secretNamePlaceholder': 'e.g., OPENAI_API_KEY',
    'secrets.secretValue': 'Secret Value',
    'secrets.secretValuePlaceholder': 'Enter the secret value',
    'secrets.description': 'Description (Optional)',
    'secrets.descriptionPlaceholder': 'Describe what this secret is used for',
    'secrets.createSecret': 'Create Secret',
    'secrets.creating': 'Creating...',
    'secrets.storedSecrets': 'Stored Secrets',
    'secrets.storedSecretsDescription': 'Your secrets are encrypted and stored securely',
    'secrets.noSecrets': 'No secrets',
    'secrets.noSecretsDescription': 'Get started by creating your first secret.',
    'secrets.lastUpdated': 'Last updated',
    'secrets.delete': 'Delete',
    'secrets.confirmDelete': 'Are you sure you want to delete secret "{name}"?',
    'secrets.securityNotice': 'Security Notice',
    'secrets.securityNotice1': '• Secrets are encrypted and stored locally on your machine',
    'secrets.securityNotice2': '• Never share your secrets or commit them to version control',
    'secrets.securityNotice3': '• Use environment variables for sensitive data in production',
    'secrets.error.loadFailed': 'Failed to load secrets',
    'secrets.error.createFailed': 'Failed to create secret',
    'secrets.error.deleteFailed': 'Failed to delete secret',
    
    // Login page
    'login.title': 'IntentOrch Login',
    'login.subtitle': 'Enter the authentication token generated by the daemon to access the management console',
    'login.authenticationToken': 'Authentication Token',
    'login.tokenPlaceholder': 'Enter the token generated by the daemon',
    'login.tokenDescription': 'Token is generated when daemon starts, you can find it in console output',
    'login.login': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.getTokenFromDaemon': 'Get Token from Daemon',
    'login.howToGetToken': 'How to get Token?',
    'login.step1': 'Start the daemon by running the following command in terminal:',
    'login.rememberToken': 'Remember this token',
    'login.rememberTokenHint': 'Auto-fill next time',
    'login.showToken': 'Show Token',
    'login.hideToken': 'Hide Token',
    'login.pasteFromClipboard': 'Paste',
    'login.clearInput': 'Clear',
    'login.daemonStatus.connected': 'Daemon connected',
    'login.daemonStatus.disconnected': 'Daemon disconnected',
    'login.daemonStatus.checking': 'Checking daemon status...',
    'login.error.cannotConnect': 'Cannot connect to daemon, please check if daemon is running',
    'login.error.authenticationFailed': 'Authentication failed',
    'login.error.tokenNotFound': 'Token not found in response from daemon',
    'login.error.cannotGetToken': 'Cannot get token from daemon',
    'login.error.invalidToken': 'Token is invalid, please check if the token is correct',
    'login.error.serverError': 'Server error, please try again later',
    'login.error.networkError': 'Network connection failed, please check your network settings',
    'login.tokenObtained': '✓ Token obtained successfully',
    'login.tokenPasted': '✓ Pasted from clipboard',
    'login.tokenCleared': 'Token cleared',
    'login.tokenRemembered': 'Token remembered, will auto-fill next time',
    'login.tokenForgotten': 'Remembered token cleared',
    'login.connecting': 'Connecting...',
    'login.retry': 'Retry',
    'login.or': 'or',
    'login.quickStart': 'Quick Start',
    'login.quickStartDesc': 'If this is your first time, start the daemon first:',
    'login.needHelp': 'Need Help?',
    'login.contactSupport': 'Contact Support',
    'login.viewDocs': 'View Docs',
    'login.tagline': 'You say it, MCP does it',
    'login.welcome': 'Welcome back',
    'login.welcomeMessage': 'Enter your authentication token to continue',
    'login.tokenInputLabel': 'Authentication token input area',
    'login.tokenHelp': 'The token is the only credential to access the management console, please keep it safe',
    'login.tokenAutoFilled': 'Saved token auto-filled',
    'login.tokenAutoFilledDesc': 'Click the "Login" button to verify',
    'login.daemonConnected': 'Daemon is running',
    'login.daemonDisconnected': 'Daemon is not running',
    'login.daemonCheckFailed': 'Unable to detect daemon status',
    'login.error.invalidFormat': 'Token format is incorrect, please check if it was copied completely',
    'login.error.tokenExpired': 'Token has expired, please obtain a new one',
    'login.error.unauthorized': 'Unauthorized, please check token permissions',
    'login.error.unknown': 'An unknown error occurred, please try again later',
    'login.tokenCopied': 'Token copied to clipboard',
    'login.copyToken': 'Copy Token',
    'login.tokenCopiedHint': 'Token copied, please keep it safe',
    'login.tokenSecurityTip': 'Do not share your token or commit it to version control',
    'login.tokenSecurityTitle': 'Security Tip',
    'login.tokenSecurityDesc': 'The token is your only credential to access the management console. Keep it safe and do not share it.',
    'login.tokenInputHelp': 'Run intentorch daemon start in terminal, copy the output token and paste it above',
    'login.tokenInputHelpTitle': 'How to get Token?',
    'login.tokenInputHelpStep1': 'Open terminal and run:',
    'login.tokenInputHelpStep2': 'Find the Token line in the output and copy the full token',
    'login.tokenInputHelpStep3': 'Paste it into the input field above and click Login',
    'login.tokenInputHelpAction': 'Copy Command',
    'login.tokenInputHelpCopied': 'Command copied',
    'login.tokenInputHelpTip': 'Tip: You can also click the button below to get the token automatically',
    'login.tokenInputHelpTipAction': 'Get Automatically',
    'login.tokenInputHelpTipDesc': 'Get token from local daemon automatically',
    'login.tokenInputHelpTipSuccess': 'Token obtained automatically',
    'login.tokenInputHelpTipFailed': 'Auto-fetch failed, please enter manually',
    'login.tokenInputHelpTipChecking': 'Fetching...',
    'login.tokenInputHelpTipRetry': 'Retry',
    'login.tokenInputHelpTipClose': 'Close',
    'login.tokenInputHelpTipError': 'Fetch failed',
    'login.tokenInputHelpTipErrorDesc': 'Unable to get token from daemon, please enter manually',
    'login.tokenInputHelpTipErrorAction': 'Enter Manually',
    'login.tokenInputHelpTipSuccessDesc': 'Token obtained successfully, please click Login',
    'login.tokenInputHelpTipSuccessAction': 'Login',
    'login.tokenInputHelpTipCheckingDesc': 'Fetching token from daemon...',
    'login.tokenInputHelpTipCheckingCancel': 'Cancel',
    'login.tokenInputHelpTipRetryDesc': 'Failed to get token, please retry or enter manually',
    'login.tokenInputHelpTipRetryAction': 'Retry',
    
    // Logs page
    'logs.title': 'Logs',
    'logs.subtitle': 'View and analyze system, Server and workflow operation logs',
    'logs.totalLogs': 'Total Logs',
    'logs.errorLogs': 'Error Logs',
    'logs.warningLogs': 'Warning Logs',
    'logs.todayLogs': 'Today Logs',
    'logs.searchPlaceholder': 'Search log content or source...',
    'logs.autoRefresh': 'Auto Refresh',
    'logs.refresh': 'Refresh',
    'logs.logLevel': 'Log Level',
    'logs.allLevels': 'All Levels',
    'logs.error': 'Error',
    'logs.warning': 'Warning',
    'logs.info': 'Info',
    'logs.debug': 'Debug',
    'logs.logSource': 'Log Source',
    'logs.allSources': 'All Sources',
    'logs.systemLogs': 'System Logs',
    'logs.serverLogs': 'Server Logs',
    'logs.workflowLogs': 'Workflow Logs',
    'logs.timeRange': 'Time Range',
    'logs.today': 'Today',
    'logs.yesterday': 'Yesterday',
    'logs.last7Days': 'Last 7 Days',
    'logs.last30Days': 'Last 30 Days',
    'logs.allTime': 'All Time',
    'logs.showingLogs': 'Showing {count} log records',
    'logs.exportLogs': 'Export Logs',
    'logs.clearLogs': 'Clear Logs',
    'logs.collapseDetails': 'Collapse details',
    'logs.expandDetails': 'Expand details',
    'logs.copyLog': 'Copy log',
    'logs.viewSourceDetails': 'View source details',
    'logs.noLogs': 'No log records',
    'logs.noLogsDescription': 'Currently no log records',
    'logs.noMatchingLogs': 'No matching log records found',
    'logs.clearAllFilters': 'Clear all filter criteria',
    'logs.levelDistribution': 'Log Level Distribution',
    'logs.levelDistributionDesc': 'Number of logs by level',
    'logs.sourceDistribution': 'Log Source Distribution',
    'logs.sourceDistributionDesc': 'Number of logs by source',
    'logs.system': 'System',
    'logs.server': 'Server',
    'logs.workflow': 'Workflow',
    'logs.logCopied': 'Log copied to clipboard',
    'logs.noLogsToExport': 'No logs to export',
    'logs.confirmClearLogs': 'Are you sure you want to clear all logs? This action cannot be undone.',
    'logs.logsCleared': 'Logs have been cleared',
    
    // Workflows page
    'workflows.title': 'Workflows',
    'workflows.description': 'Create and manage automation workflows',
    'workflows.createWorkflow': 'Create Workflow',
    'workflows.totalWorkflows': 'Total Workflows',
    'workflows.executedWorkflows': 'Executed Workflows',
    'workflows.neverExecutedWorkflows': 'Never Executed Workflows',
    'workflows.workflowsWithSteps': 'Workflows with Steps',
    'workflows.noWorkflows': 'No Workflows',
    'workflows.confirmDelete': 'Are you sure you want to delete workflow "{name}"?',
    'workflows.searchPlaceholder': 'Search workflow name or description...',
    'workflows.filterAll': 'All Workflows',
    'workflows.filterHasSteps': 'Has Steps',
    'workflows.filterExecuted': 'Executed',
    'workflows.filterNeverExecuted': 'Never Executed',
    'workflows.exportAll': 'Export All Workflows',
    'workflows.importWorkflow': 'Import Workflow',
    'workflows.refresh': 'Refresh',
    'workflows.createModalTitle': 'Create Workflow',
    'workflows.createModalSubtitle': 'Create new automation workflow',
    'workflows.editModalTitle': 'Edit Workflow',
    'workflows.editModalSubtitle': 'Edit workflow basic information',
    'workflows.nameRequired': 'Workflow Name *',
    'workflows.descriptionOptional': 'Description (Optional)',
    'workflows.cancel': 'Cancel',
    'workflows.save': 'Save',
    'workflows.creating': 'Creating...',
    'workflows.saving': 'Saving...',
    'workflows.execute': 'Execute',
    'workflows.edit': 'Edit',
    'workflows.duplicate': 'Duplicate',
    'workflows.exportJson': 'Export as JSON',

    // Orchestration
    'orchestration.title': 'Intent Orchestration',
    'orchestration.aiAssistant': 'AI Assistant',
    'orchestration.subtitle': 'Generate automation workflows automatically using natural language',
    'orchestration.chatPlaceholder': 'Describe your automation needs...',
    'orchestration.inputPlaceholder': 'Enter your intent',
    'orchestration.sendButton': 'Send (Enter)',
    'orchestration.analyzing': 'Analyzing intent...',
    'orchestration.publish': 'Publish Workflow',
    'orchestration.clear': 'Clear Draft',
    'orchestration.noDraft': 'No Draft Steps',
    'orchestration.capabilityMissing': 'Capability Not Found',
    'orchestration.capabilityMissingDesc': "I couldn't find a matching MCP server or tool to satisfy your intent.",
    'orchestration.submitRequest': 'Submit Tool Request',
    'orchestration.workflowGenerated': "I've generated a workflow with {count} steps for you. Please review the steps on the right and execute.",
    'orchestration.executionComplete': 'Workflow execution completed.',
    'orchestration.formattingFailed': 'Workflow execution completed, but result formatting failed.',
    'orchestration.generatingWorkflow': 'Generating workflow...',
    'orchestration.executeNow': 'Execute Now',
    'orchestration.executeNowDesc': 'Save and execute immediately',
    'orchestration.saveOnly': 'Save Only',
    'orchestration.saveOnlyDesc': 'Save for later execution',
    'orchestration.editSteps': 'Edit Steps',
    'orchestration.editStepsDesc': 'Review and modify steps',
    'orchestration.stepsGenerated': '{count} steps generated',
    'orchestration.clearAllSteps': 'Clear all steps',
    'orchestration.selectAction': 'Select action',
    'orchestration.executing': 'Executing...',
    'orchestration.go': 'Go',
    'orchestration.chooseAction': 'Choose Action',
    'orchestration.actionTip': 'Tip: The selected action will be remembered for next time',
    'orchestration.addStepManually': 'Add step manually',
    'orchestration.contactSupport': 'Contact Support',
    'orchestration.failedToGenerate': 'Failed to generate workflow. Please try rephrasing your intent.',
    'orchestration.draftMode': 'Draft Mode • Autosaved locally',
    'orchestration.executingWorkflow': 'Executing Workflow',
    'orchestration.pleaseWaitWorkflow': 'Please wait, workflow is being executed...',
    'orchestration.poweredBy': 'Powered by Intentorch Reasoning Engine',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // 从localStorage读取保存的语言设置，默认为浏览器语言或中文
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'zh' || saved === 'en')) {
      return saved;
    }
    
    // 检测浏览器语言
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('zh')) {
      return 'zh';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    const langTranslations = translations[language] as Record<string, string>;
    const englishTranslations = translations['en'] as Record<string, string>;
    let text = langTranslations[key] || englishTranslations[key] || key;
    
    // 替换参数
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param]);
      });
    }
    
    return text;
  };

  useEffect(() => {
    // 设置html lang属性
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

